#!/bin/bash
set -euo pipefail

urlencode() {
    LC_COLLATE=C
    
    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%%%02X' "'$c" ;;
        esac
    done
}

if [ -z "${1-}" ]; then
    echo "usage: $0 <file>" >&2
    exit 2
fi
mimetype=$(file -bN --mime-type "$1")

uri64="data:$mimetype;base64,$(base64 < "$1")"
uriplain="data:$mimetype,$(urlencode "$(cat "$1")")"
if [ ${#uriplain} -lt ${#uri64} ]
then echo "${uriplain}"
else echo "${uri64}"
fi
