#!/bin/bash
# Custom version of imgcat using escape codes documented at https://iterm2.com/documentation-images.html

set -e
set -u
set -o pipefail

help() {
  echo "usage: $0 [--height <height>] { file | url }..."
  echo
  echo "Outputs images to the terminal using iTerm2 escape codes."
  echo
}

usage_error() {
  echo "error: $*"
  echo
  help
  exit 2
} >&2

height=auto

while (( $# > 0 )); do
    case "$1" in
        --height) shift; height="$1";;
        -'?' | --help) help; exit;;
        --) shift; break;;
        -*) usage_error "unknown option $1" "Use '--' to separate arguments from options";;
        *) break;;
    esac
    shift
done

[ $# -gt 0 ] || usage_error "no files or URLs provided"

function show_image() {
    printf '\033]1337;File=name=%s;height=%s;size=%d;inline=1:%s\a\n' \
        "$(printf %s "$1" | base64)" \
        "${height}" \
        "$(cat "$1" | wc -c)" \
        "$(base64 <"$1")" \
        ;
}

for img in "$@"; do
    if [[ "${img}" == http:* ]] || [[ "${img}" == https:* ]]; then
        file="$(basename "$1")"
        curl --silent --fail "${img}" > "${file}"
        show_image "${file}"
        rm "${file}"
    elif [ -r "${img}" ]; then
        show_image "${img}"
    else
        echo "File ${img} does not exist or is not readable." >&2
        exit 1
    fi
done
