#!/bin/bash
# Output images to the terminal using iTerm2

set -e
set -u
set -o pipefail

if [ $# -eq 0 ]; then
    echo "Usage: imgcat { file | url }..."
    exit 1
fi

function show_image() {
    printf '\033]1337;File=name='`echo -n "$1" | base64`";"
    wc -c "$1" | awk '{printf "size=%d",$1}'
    printf ";inline=1"
    printf ":"
    base64 < "$1"
    printf '\a\n'
}

for img in "$@"; do
    if [[ "${img}" == http:* ]] || [[ "${img}" == https:* ]]; then
        file="$(basename "$1")"
        curl --silent --fail "${img}" > "${file}"
        show_image "${file}"
        rm "${file}"
    elif [ -r "${img}" ]; then
        show_image "${img}"
    else
        echo "File ${img} does not exist or is not readable." >&2
        exit 1
    fi
done
