#!/bin/bash
set -euo pipefail

echo "Getting your weather forecast"
weather

echo "Getting your upcoming events"
cd "$HOME/open-source/programmiersportgruppe/pony-calendar"
    bundle exec ./pony-calendar.rb
cd -
echo

echo "Checking for brew updates"
brew up

brew_doctor() {
    echo "Checking in with the brew doctor"
    if [ -f ~/.accepted-brew-doctor-output ]; then
        diff ~/.accepted-brew-doctor-output <(brew doctor 2>&1)
    else
        brew doctor
    fi
}
brew_doctor

outdated="$(brew outdated)"
if [ -n "${outdated}" ]; then
    echo
    echo "Outdated packages:"
    brew outdated
    brew upgrade
    brew_doctor
fi

echo "Fully removing the brew cache"
rm -rf "$(brew --cache)"  # as specified by `brew cleanup --help`

# echo "Updating cabal"
# cabal update

echo "Testing connections to configured SSH hosts"
test-ssh-configuration
